### ISSUE TITLE
Returns found for Instagram, even when the user does not exist

### ISSUE THREAD

**Issue by TheWizardBear** [checkerschaf/sherlock-deno#2]
Deno version: 1.5.0
Sherlock version: 1.8.0

```
[>] Input username:  09sdfhksjhdf9223wedsf
[+] Instagram: https://www.instagram.com/09sdfhksjhdf9223wedsf

Finished in 6 seconds.
Found a total of 1 matches across 276 sites.
```

**Comment by checkerschaf** [comment]
Hi,
thanks for the report. 🕵️‍♂️
I've created a [new release v1.8.2](https://github.com/checkerschaf/sherlock-deno/releases/tag/v1.8.2) that fixes this issue. Please see the [README](https://github.com/checkerschaf/sherlock-deno#how-to-update-the-cli) on how to upgrade to the new version and feel free to reopen this issue/create a new issue if you find any bugs/site errors.
Have a nice day! 👋
